### PR TITLE
feat: Add error handling to getLoginRequest function

### LINKED ISSUE #68: Kotlin internal error exposed by the API
When a login request is issued to the Wallet API without correctly filling in the required parameters, the API returns an internal Kotlin error. 

image

For the sake of API semantics, wouldn't it be better if we encapsulated this internal language error in an error more related to the authentication process?

[]s

### PR DESCRIPTION
**Pull request by SuperBatata**
## Description

adds error handling to the getLoginRequest function in our application. The changes ensure that any issues with the incoming request parameters are properly caught and handled, providing clear and descriptive error messages.

Fixes #68

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by mikeplotean — CHANGES_REQUESTED** [review]

**Comment by alegomes** [comment]
I tried to reproduce the issue #68.

image

It's better than "Polymorphic serializer..." error. However, it's still not a descriptive enough message. "Invalid request format" is quite vague, imo. "Invalid request BODY format" would be better, but still doesn't show me what exactly is wrong. 

Couldn't we just validate the body request and return something like "Missing 'type' field in the request body"?

**Comment by alegomes** [comment]
Another point: is it just me or are there a lot more file changes in the PR than there should be for "Add error handling to the getLoginRequest function"?

**Comment by alegomes** [comment]
Last but not least: The 500 status code return. I think [400](https://www.rfc-editor.org/rfc/rfc9110.html#name-400-bad-request) is more appropriate, no? 

> The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

**Comment by mikeplotean** [comment]
> Another point: is it just me or are there a lot more file changes in the PR than there should be for "Add error handling to the getLoginRequest function"?

that must be because of merging main into it

**Pull request closed without merging**
